apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.sqlType}}
spec:
  selector:
    matchLabels:
      app: {{.Values.sqlType}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{.Values.sqlType}}
    spec:
      containers:
      - image: {{ .Values.sqlType}}:{{ .Values.sqlImageTag }}
        name: {{.Values.sqlType}}
        envFrom:
          - secretRef:
              name: {{ .Values.name }}-{{ .Values.sqlType }}-secret
        ports:
        - containerPort: 3306
          name: {{.Values.sqlType}}
        volumeMounts:
        - name: {{.Values.sqlType}}-persistent-storage
          mountPath: /var/lib/{{.Values.sqlType}}
      volumes:
      - name: {{.Values.sqlType}}-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Values.name }}-{{.Values.sqlType}}-pv-claim

