# Creates a script that adds a generic namespace user that has access to the namespace database
apiVersion: batch/v1
kind: Job
metadata:
  name: initialize-{{.Values.sqlType}}-{{.Values.name}}
spec:
  backoffLimit: 4
  template:
    metadata:
      name: name
    spec:
      restartPolicy: OnFailure
      containers:
        - name: run-sql
          image: postgres:latest  # This image includes the psql client
          command: ["/bin/bash", "-c"]
          envFrom:
            - secretRef:
                name: {{ .Values.name }}-{{ .Values.sqlType }}-secret
          args:
            - |
              #!/bin/bash
              set -e

              echo "CREATE USER {{snakecase .Values.name}} WITH PASSWORD '$POSTGRES_PASSWORD'; CREATE DATABASE {{snakecase .Values.name}}; ALTER DATABASE {{.Values.name}} OWNER TO {{snakecase .Values.name}};" > script.sql 
              SERVICE="{{ .Values.sqlType}}"
              DB_USER="postgres"
              echo "Running SQL file"
              PGPASSWORD=$POSTGRES_PASSWORD psql -h $SERVICE -U $DB_USER -f script.sql
