# Creates a script that adds a generic namespace user that has access to the namespace database
apiVersion: batch/v1
kind: Job
metadata:
  name: initialize-{{.Values.sqlType}}-{{.Values.name}}
spec:
  backoffLimit: 4
  template:
    metadata:
      name: name
    spec:
      restartPolicy: OnFailure
      containers:
        - name: run-sql
          image: postgres:latest  # This image includes the psql client
          command: ["/bin/bash", "-c"]
          envFrom:
            - secretRef:
                name: {{ .Values.name }}-{{ .Values.sqlType }}-secret
          args:
            - |
              #!/bin/bash
              set -e

              echo "CREATE USER {{.Values.name}} WITH PASSWORD '$POSTGRES_PASSWORD';\n CREATE DATABASE {{.Values.name}};\n ALTER DATABASE {{.Values.name}} OWNER TO {{.Values.name}};" > script.sql 
              SERVICE="{{ .Values.sqlType}}"
              DB_NAME="{{ .Values.name}}"
              DB_USER="postgres"
              PGPASSWORD=$POSTGRES_PASSWORD
              echo "Running SQL file"
              psql -h $SERVICE -U $DB_USER -d $DB_NAME -f script.sql
